### ISSUE TITLE
STM32L476RCT6 use freertos and sdio 4bits and dma,can not receive queue

### ISSUE THREAD

**Issue by Barfell** [STMicroelectronics/stm32l4xx_hal_driver#10]
STM32L476RCT6, use CUBEMX generate the project, use FREERTOS ,SDIO 4bits, DMA, and Fatfs, the SD not work normally, the library is STM32Cube_FW_L4_V1.18.0, the question repetition on other library 
in fuction
 DRESULT SD_read(BYTE lun, BYTE *buff, DWORD sector, UINT count), 
    event = osMessageGet(SDQueueID, SD_TIMEOUT);

can not receive message.

but use sdio 1bits，work normally.

**Comment by Barfell** [comment]
set a break in the function void SDMMC1_IRQHandler(void),then full running,the sd init success.why?

**Comment by TOUNSTM** [comment]
Hello @Barfell,

Thank you for your contribution. Regarding the point for which you opened the issue, as it is resolved, please allow me to close the issue.

With regards,
