### ISSUE TITLE
Compatibility information missing for v1.13.4

### ISSUE THREAD

**Issue by OParczyk** [STMicroelectronics/stm32l4xx_hal_driver#16]
The Compatibility information table in the README is missing the set of versions to use with the latest release tag (v1.13.4).
Could you please add it?

**Comment by ALABSTM** [comment]
Hi @OParczyk,

Thank you for this heads-up. Actually, this table shall be removed as it is not easily maintainable and potentially subject to oversight as you may have noticed.

The new proposed way is to check the compatibility information directly in the release note of the STM32CubeL4 firmware repository, which the link to is provided in the `README.md`, in the [Compatibility information](https://github.com/STMicroelectronics/stm32l4xx_hal_driver/blob/master/README.md#compatibility-information) section.

Once the release note is open, you can check the `Drivers` table, as shown below.

![image](https://github.com/STMicroelectronics/stm32l4xx_hal_driver/assets/46019491/fde1a600-000d-4140-ac04-198c4838ef4c)

I hope this addresses your request.

With regards,

**Comment by ALABSTM** [comment]
Fixed in commit 75636e1a2ee30f28a0b301138c8b8fc0e424e7ae

**Comment by ALABSTM** [comment]
Hi @OParczyk,

Issue just fixed. Please allow me to close this thread. Thank you again for having reported.

With regards,
