### ISSUE TITLE
tm32l4xx_hal_cortex.h two function prototyps on one line

### ISSUE THREAD

**Issue by RetoFx** [STMicroelectronics/stm32l4xx_hal_driver#19]
Hi 
In File tm32l4xx_hal_cortex.h Line 300 are two function prototyps on one line

void HAL_MPU_DisableRegion(uint32_t RegionNumber);void HAL_MPU_ConfigRegion(MPU_Region_InitTypeDef *MPU_Init);

**Comment by TOUNSTM** [comment]
Hello @RetoFx,

Thank you for your contribution. You are absolutely right about this point.
Actually, the point you raised has already been dealt and fixed internally. You can find the fix in this commit : dd06af553597bb0d540532c486796a6064376f2b

Thank you again for your contribution. We are looking forward to reading from you again.
With regards,
