### ISSUE TITLE
FLASH_SIZE define is missing

### ISSUE THREAD

**Issue by josesimoes** [STMicroelectronics/stm32l4xx_hal_driver#4]
**Describe the set-up**
- Using the latest tag in this repo. Along with cmsis_device_l4 v1.7.2.

**Describe the bug**
- On build I get this: 
`error: 'FLASH_SIZE' undeclared`

**Comment by RKOUSTM** [comment]
Hi @josesimoes,

Thank you for your report. We tried to reproduce the issue you described, but we couldn't notice the problem. Could you please give us more details about the problem that lead to this issue. 

With regards,

**Comment by josesimoes** [comment]
Hey! I ended up not needing the code that was causing this. Thanks anyway.
