### ISSUE TITLE
TX IRQ remains active after HAL_I2C_Mem_Read_DMA

### ISSUE THREAD

**Issue by accabog** [STMicroelectronics/stm32l4xx_hal_driver#7]
Because HAL_I2C_Mem_Read_DMA MemAddress transmission is based on TX IRQ

https://github.com/STMicroelectronics/stm32l4xx_hal_driver/blob/a4d4011e08abea42cb6cbb7764e1a0c4e91c6fb5/Src/stm32l4xx_hal_i2c.c#L3079
neither I2C_Mem_ISR_DMA nor I2C_ITMasterCplt will not disable the TX IRQ after the data transfer
https://github.com/STMicroelectronics/stm32l4xx_hal_driver/blob/a4d4011e08abea42cb6cbb7764e1a0c4e91c6fb5/Src/stm32l4xx_hal_i2c.c#L5937
Therefore, if a non-IT based transmission such as HAL_I2C_Mem_Write will follow, a TX irq will be triggered without any interrupt callback defined, therefore the IRQ cannot be cleared and results in the program stuck in I2C ISR

One solution is to call I2C_Disable_IRQ(hi2c, I2C_XFER_TX_IT); also for the state HAL_I2C_STATE_BUSY_RX in I2C_ITMasterCplt

**Comment by HBOSTM** [comment]
ST Internal Reference: 145679
