### ISSUE TITLE
HAL_SPI_TransmitReceive() always returns HAL_BUSY after the first transaction

### ISSUE THREAD

**Issue by by-gnome** [STMicroelectronics/stm32l4xx_hal_driver#8]
In HAL_SPI_TransmitReceive() the hspi->State variable remains in HAL_SPI_STATE_BUSY_RX after the first transaction, no further transactions are executed, HAL_BUSY is returned.

It can be solved like this:
```
1545-
1546-    errorcode = HAL_ERROR;

1553-    errorcode = HAL_ERROR;

1557+    if (hspi->ErrorCode != HAL_SPI_ERROR_NONE)
1558+    {
1559+      errorcode = HAL_ERROR;
1560+    }
1561+      else
1562+    {
1563+      hspi->State = HAL_SPI_STATE_READY;
1564+    }
1565+
```

**Comment by TOUNSTM** [comment]
Hello @by-gnome,

Thank you for reporting this point. Actually, this point has been discussed and fixed internally, before we receive your request. The fix will be available soon hopefully.

With Regards,
Tasnim

**Comment by TOUNSTM** [comment]
ST Internal Reference: 135724
